name: Waka Readme
on:
  workflow_dispatch:
  schedule:
    # Runs at every 1 min
    - cron: '*/25 * * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BLOCKS: ▱▰
          TIME_RANGE: "all_time"
          SHOW_TIME: true
          SHOW_PROJECTS: false
          SHOW_LINES_OF_CODE: true
          SHOW_LOC_CHART: true
          SHOW_MASKED_TIME: true
          LOCALE: "en"

# name: Waka Readme

# on:
# workflow_dispatch:
# schedule:
# Runs at every 30 min
#  - cron: "30 * * * *"

#jobs:
# update-readme:
#  name: Update this repo's README
# runs-on: ubuntu-latest
#steps:
# - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
#  with:
#   WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#  GH_TOKEN: ${{ secrets.GH_TOKEN }}
# BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
#TIME_RANGE: "all_time"
# SHOW_PROJECTS: false
# SHOW_LINES_OF_CODE: true
# SHOW_LOC_CHART: true
# LOCALE: "en"

# Warning: Unexpected input(s) 'BLOCKS', 'TIME_RANGE', 'SHOW_TIME', 'SHOW_MASKED_TIME', valid inputs are ['entryPoint', 'args', 'GH_TOKEN', 'WAKATIME_API_KEY', 'PUSH_BRANCH_NAME', 'SHOW_OS', 'SHOW_PROJECTS', 'SHOW_EDITORS', 'SHOW_TIMEZONE', 'SHOW_COMMIT', 'SHOW_LANGUAGE', 'SHOW_LINES_OF_CODE', 'SHOW_LANGUAGE_PER_REPO', 'SHOW_LOC_CHART', 'SHOW_DAYS_OF_WEEK', 'SHOW_PROFILE_VIEWS', 'SHOW_SHORT_INFO', 'LOCALE', 'COMMIT_BY_ME', 'IGNORED_REPOS', 'COMMIT_MESSAGE', 'COMMIT_USERNAME', 'COMMIT_EMAIL', 'SHOW_UPDATED_DATE', 'UPDATED_DATE_FORMAT', 'SHOW_TOTAL_CODE_TIME', 'SYMBOL_VERSION']
